# Generated by Django 5.2.4 on 2025-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriasAtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
            options={
                'db_table': 'categorias_atend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dia', models.DateField(blank=True, null=True)),
                ('data_chamado', models.DateTimeField()),
                ('data_finalizacao', models.DateTimeField()),
                ('descricao_problema', models.TextField()),
                ('nivel_atendimento_cliente', models.IntegerField()),
                ('titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'chamados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Computadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('modelo', models.CharField(max_length=200)),
                ('endereco_mac', models.CharField(max_length=17, unique=True)),
                ('marca_processador', models.CharField(max_length=200)),
                ('frequencia_processador', models.DecimalField(decimal_places=2, max_digits=4)),
                ('velocidade_memoria', models.IntegerField()),
                ('tamanho_memoria', models.IntegerField()),
                ('tipo_armazenamento', models.TextField()),
                ('tamanho_armazenamento', models.IntegerField()),
                ('versao_so', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('potencia_fonte', models.IntegerField()),
                ('ip_dispositivo', models.GenericIPAddressField(unique=True)),
                ('data_instalacao', models.DateField()),
            ],
            options={
                'db_table': 'computadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dispositivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailsAntigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_email', models.CharField(max_length=100)),
                ('tamanho_email', models.IntegerField()),
                ('senha', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'emails_antigos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailsNovos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_email', models.CharField(max_length=100)),
                ('tamanho_email', models.IntegerField()),
                ('senha', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'emails_novos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_host', models.CharField(max_length=100)),
                ('ip_host', models.GenericIPAddressField(unique=True)),
            ],
            options={
                'db_table': 'hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impressoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=45)),
                ('toner', models.CharField(max_length=45)),
                ('nome_impressora', models.CharField(max_length=150)),
                ('proprietario', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('tipo_conexao', models.TextField()),
                ('ip_dispositivo', models.GenericIPAddressField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'impressoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginUsuarioPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login_usuario_pc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PastaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pasta_publica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoManuPrevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manu', models.DateField()),
                ('descricao', models.TextField()),
                ('situacao', models.TextField()),
            ],
            options={
                'db_table': 'plano_manu_prevent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roteadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('endereco_mac', models.CharField(max_length=17, unique=True)),
                ('ip_dispositivo', models.GenericIPAddressField(unique=True)),
                ('data_instalacao', models.DateField()),
            ],
            options={
                'db_table': 'roteadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('endereco_mac', models.CharField(max_length=17, unique=True)),
                ('marca_processador', models.CharField(max_length=200)),
                ('frequencia_processador', models.DecimalField(decimal_places=2, max_digits=4)),
                ('velocidade_memoria', models.IntegerField()),
                ('tamanho_memoria', models.IntegerField()),
                ('tipo_armazenamento', models.TextField()),
                ('tamanho_armazenamento', models.IntegerField()),
                ('versao_so', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('express_code', models.CharField(max_length=100)),
                ('service_tag', models.CharField(max_length=45, unique=True)),
                ('ip_dispositivo', models.GenericIPAddressField(unique=True)),
                ('data_instalacao', models.DateField()),
            ],
            options={
                'db_table': 'servidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'setores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treinamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_id', models.IntegerField()),
                ('descricao', models.TextField()),
                ('data_trei', models.DateField(blank=True, null=True)),
                ('data_ts_treinamento', models.DateTimeField()),
                ('data_finalizacao', models.DateTimeField()),
                ('titulo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'treinamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('senha_hash', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=150)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
